image: bradrydzewski/python:2.7-scrapinghub

script:
  - git restore-mtime

publish:
  docker:
    docker_host: $DOCKER_HOST
    image_name: i.scrapinghub.com/storm/0.9.4:{version}
    keep_build: true
